### ISSUE TITLE
logs not logging anything

### ISSUE THREAD

**Issue by SeriusDavid** [limcross/webpay_rails#6]
webpay.log its always empty i dont know why and i need it for the certification

**Comment by limcross** [comment]
Are you using the master version? Until version 1.1.0 the log was only in the rails logs. The master version is not stable, prefer the releases. A new version has just been published with the logging feature running according to the latest documentation.

**Comment by SeriusDavid** [comment]
Hola, utilizo la versión release en esta tengo el webpay.log que aparece en
la documentación pero este siempre está vacío en los logs de el servidor
aparece toda la información obtenida por transbank pero en los logs aparte
no aparece nada.
Revisaré la nueva versión y te comentare que tal.
Tu gema de todas maneras esta increible gracias
