### ISSUE TITLE
Error al poner certificados de producción  

### ISSUE THREAD

**Issue by CarlosIgnacioGo** [limcross/webpay_rails#7]
Este error surgió cuando cambie las claves de integración a los certificados de producción, ¿alguna idea de lo que podría llegar a ser?

![captura de pantalla 2018-07-20 a las 11 23 36](https://user-images.githubusercontent.com/12127440/43013707-632830d2-8c0f-11e8-86a6-e2ef3210be55.png)

**Comment by limcross** [comment]
Este error ocurre cuando el certificado público o llave privada no es válida.

_Lamento lo tarde, de mi respuesta._
